name: Build & Package Game

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-cache: npm
          node-version: 20

      - name: Install Dependencies
          # clean install
        run: npm ci

      - name: Build Game
        run: npm run build

      - name: Zip Build Output
        run: |
          cd dist
          zip -r ../game.zip .
          cd ..

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: panel-attack-clone-html5
          path: game.zip

